# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import onlinetest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='quesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_paper_id', models.CharField(max_length=50, unique=True)),
                ('client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=500)),
                ('questionType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='studentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_paper_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('marks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='studentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('institute', models.CharField(default=None, max_length=50)),
                ('client', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=250)),
                ('test_marks', models.CharField(max_length=30)),
                ('test_questions', models.CharField(max_length=30)),
                ('test_time', models.CharField(max_length=30)),
                ('test_file', models.FileField(default='', upload_to=onlinetest.models.content_file_name)),
                ('test_number', models.CharField(max_length=30)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
