# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_paper_id', models.CharField(max_length=50, unique=True)),
                ('client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=500)),
                ('questionType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='studentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_paper_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('marks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='studentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('institute', models.CharField(default=None, max_length=50)),
                ('client', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('pwd', models.CharField(max_length=80)),
            ],
        ),
    ]
